name: Release BackApp

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  checks: write

jobs:
  build-and-test:
    uses: ./.github/workflows/binary.test.yml
    with:
      build_architecture: 'all'
    secrets: inherit
  release:
    name: Publish release
    needs: build-and-test
    if: ${{ needs.build-and-test.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux amd64 artifact
        uses: actions/download-artifact@v4
        with:
          name: backapp-server-linux-amd64
          path: artifacts

      - name: Download Linux arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: backapp-server-linux-arm64
          path: artifacts

      - name: Download Linux armv7 artifact
        uses: actions/download-artifact@v4
        with:
          name: backapp-server-linux-armv7
          path: artifacts

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.workflow_run.head_branch }}
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker_publish_latest:
    name: Build and Push Docker (latest)
    needs: build-and-test
    if: ${{ needs.build-and-test.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and publish Docker image
        uses: Dennis960/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          context: .
          image_tag: latest
